name: Build and Deploy EmpAudit

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Connexion Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-bda:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/projet-bda:latest
